#!/usr/bin/env python3

import os
import sys
import yaml

def eprint(*args, **kwargs):
    """
    Print to stderr.
    """
    kwargs['file'] = sys.stderr
    print(*args, **kwargs)

def run_plugin():
    """
    execv() the configured path.
    """
    try:
        with open(sys.argv[1], 'r') as f:
            plugin_config = yaml.safe_load(f)
            path = plugin_config.get('path')
        if not path:
            eprint('path is required')
            sys.exit(1)
        os.execv(path, sys.argv)
    except Exception as e:
        if path:
            eprint('%s: %s' % (path, e))
        else:
            eprint(e)
        sys.exit(1)

if __name__ == '__main__':
    run_plugin()
